apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-api-credentials
  namespace: {{ .Values.app.namespace.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: my-api-credentials
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: secrets/my-api/credentials
        property: api_key
