stages:
  - lint
  - publish

lint:
  stage: lint
  image: alpine/helm:latest
  script:
    - helm lint charts/app-deployer
    - helm lint charts/build-deployer

publish:
  stage: publish
  image: alpine/helm:latest
  script:
    - helm package charts/app-deployer
    - helm package charts/build-deployer
    - >-
      curl --request POST
      --form "chart=@app-deployer-${CI_COMMIT_TAG}.tgz"
      --user "gitlab-ci-token:${CI_JOB_TOKEN}"
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"
    - >-
      curl --request POST
      --form "chart=@build-deployer-${CI_COMMIT_TAG}.tgz"
      --user "gitlab-ci-token:${CI_JOB_TOKEN}"
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"
  rules:
    - if: $CI_COMMIT_TAG
