{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app-deployer.name" . }}
  namespace: {{ include "app-deployer.namespace" . }}
  labels:
    {{- include "app-deployer.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "app-deployer.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        {{- range .Values.ports }}
        - port: {{ .containerPort }}
          protocol: {{ .protocol | default "TCP" }}
        {{- end }}
{{- end }}
