{{- if .Values.waypoint.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: waypoint
  namespace: {{ include "app-deployer.namespace" . }}
  labels:
    istio.io/waypoint-for: {{ .Values.waypoint.waypointFor }}
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
{{- end }}
